# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:41:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Label(Enum):
    ACCOUNT_DEFENDER_LABEL_UNSPECIFIED = 'ACCOUNT_DEFENDER_LABEL_UNSPECIFIED'
    PROFILE_MATCH = 'PROFILE_MATCH'
    SUSPICIOUS_LOGIN_ACTIVITY = 'SUSPICIOUS_LOGIN_ACTIVITY'
    SUSPICIOUS_ACCOUNT_CREATION = 'SUSPICIOUS_ACCOUNT_CREATION'
    RELATED_ACCOUNTS_NUMBER_HIGH = 'RELATED_ACCOUNTS_NUMBER_HIGH'


class GoogleCloudRecaptchaenterpriseV1AccountDefenderAssessment(BaseModel):
    labels: Optional[List[Label]] = Field(None, description='Labels for this request.')


class LatestVerificationResult(Enum):
    RESULT_UNSPECIFIED = 'RESULT_UNSPECIFIED'
    SUCCESS_USER_VERIFIED = 'SUCCESS_USER_VERIFIED'
    ERROR_USER_NOT_VERIFIED = 'ERROR_USER_NOT_VERIFIED'
    ERROR_SITE_ONBOARDING_INCOMPLETE = 'ERROR_SITE_ONBOARDING_INCOMPLETE'
    ERROR_RECIPIENT_NOT_ALLOWED = 'ERROR_RECIPIENT_NOT_ALLOWED'
    ERROR_RECIPIENT_ABUSE_LIMIT_EXHAUSTED = 'ERROR_RECIPIENT_ABUSE_LIMIT_EXHAUSTED'
    ERROR_CRITICAL_INTERNAL = 'ERROR_CRITICAL_INTERNAL'
    ERROR_CUSTOMER_QUOTA_EXHAUSTED = 'ERROR_CUSTOMER_QUOTA_EXHAUSTED'
    ERROR_VERIFICATION_BYPASSED = 'ERROR_VERIFICATION_BYPASSED'
    ERROR_VERDICT_MISMATCH = 'ERROR_VERDICT_MISMATCH'


class GoogleCloudRecaptchaenterpriseV1AndroidKeySettings(BaseModel):
    allowAllPackageNames: Optional[bool] = Field(
        None, description='If set to true, allowed_package_names are not enforced.'
    )
    allowedPackageNames: Optional[List[str]] = Field(
        None,
        description="Android package names of apps allowed to use the key. Example: 'com.companyname.appname'",
    )
    supportNonGoogleAppStoreDistribution: Optional[bool] = Field(
        None,
        description='Set to true for keys that are used in an Android application that is available for download in app stores in addition to the Google Play Store.',
    )


class Annotation(Enum):
    ANNOTATION_UNSPECIFIED = 'ANNOTATION_UNSPECIFIED'
    LEGITIMATE = 'LEGITIMATE'
    FRAUDULENT = 'FRAUDULENT'
    PASSWORD_CORRECT = 'PASSWORD_CORRECT'
    PASSWORD_INCORRECT = 'PASSWORD_INCORRECT'


class Reason(Enum):
    REASON_UNSPECIFIED = 'REASON_UNSPECIFIED'
    CHARGEBACK = 'CHARGEBACK'
    CHARGEBACK_FRAUD = 'CHARGEBACK_FRAUD'
    CHARGEBACK_DISPUTE = 'CHARGEBACK_DISPUTE'
    REFUND = 'REFUND'
    REFUND_FRAUD = 'REFUND_FRAUD'
    TRANSACTION_ACCEPTED = 'TRANSACTION_ACCEPTED'
    TRANSACTION_DECLINED = 'TRANSACTION_DECLINED'
    PAYMENT_HEURISTICS = 'PAYMENT_HEURISTICS'
    INITIATED_TWO_FACTOR = 'INITIATED_TWO_FACTOR'
    PASSED_TWO_FACTOR = 'PASSED_TWO_FACTOR'
    FAILED_TWO_FACTOR = 'FAILED_TWO_FACTOR'
    CORRECT_PASSWORD = 'CORRECT_PASSWORD'
    INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'
    SOCIAL_SPAM = 'SOCIAL_SPAM'


class GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentResponse(BaseModel):
    pass


class GoogleCloudRecaptchaenterpriseV1ChallengeMetrics(BaseModel):
    failedCount: Optional[str] = Field(
        None,
        description='Count of submitted challenge solutions that were incorrect or otherwise deemed suspicious such that a subsequent challenge was triggered.',
    )
    nocaptchaCount: Optional[str] = Field(
        None,
        description='Count of nocaptchas (successful verification without a challenge) issued.',
    )
    pageloadCount: Optional[str] = Field(
        None,
        description='Count of reCAPTCHA checkboxes or badges rendered. This is mostly equivalent to a count of pageloads for pages that include reCAPTCHA.',
    )
    passedCount: Optional[str] = Field(
        None,
        description='Count of nocaptchas (successful verification without a challenge) plus submitted challenge solutions that were correct and resulted in verification.',
    )


class GoogleCloudRecaptchaenterpriseV1EndpointVerificationInfo(BaseModel):
    emailAddress: Optional[str] = Field(
        None, description='Email address for which to trigger a verification request.'
    )
    lastVerificationTime: Optional[str] = Field(
        None,
        description='Output only. Timestamp of the last successful verification for the endpoint, if any.',
    )
    phoneNumber: Optional[str] = Field(
        None,
        description='Phone number for which to trigger a verification request. Should be given in E.164 format.',
    )
    requestToken: Optional[str] = Field(
        None,
        description='Output only. Token to provide to the client to trigger endpoint verification. It must be used within 15 minutes.',
    )


class GoogleCloudRecaptchaenterpriseV1FirewallActionAllowAction(BaseModel):
    pass


class GoogleCloudRecaptchaenterpriseV1FirewallActionBlockAction(BaseModel):
    pass


class GoogleCloudRecaptchaenterpriseV1FirewallActionRedirectAction(BaseModel):
    pass


class GoogleCloudRecaptchaenterpriseV1FirewallActionSetHeaderAction(BaseModel):
    key: Optional[str] = Field(
        None, description='The header key to set in the request to the backend server.'
    )
    value: Optional[str] = Field(
        None,
        description='The header value to set in the request to the backend server.',
    )


class GoogleCloudRecaptchaenterpriseV1FirewallActionSubstituteAction(BaseModel):
    path: Optional[str] = Field(
        None,
        description='The address to redirect to. The target is a relative path in the current host. Example: "/blog/404.html".',
    )


class GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentBehavioralTrustVerdict(
    BaseModel
):
    trust: Optional[float] = Field(
        None,
        description='Probability (0-1) of this transaction attempt being executed in a behaviorally trustworthy way.',
    )


class GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentCardTestingVerdict(
    BaseModel
):
    risk: Optional[float] = Field(
        None,
        description='Probability (0-1) of this transaction attempt being part of a card testing attack.',
    )


class GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentStolenInstrumentVerdict(
    BaseModel
):
    risk: Optional[float] = Field(
        None,
        description='Probability (0-1) of this transaction being executed with a stolen instrument.',
    )


class GoogleCloudRecaptchaenterpriseV1IOSKeySettings(BaseModel):
    allowAllBundleIds: Optional[bool] = Field(
        None, description='If set to true, allowed_bundle_ids are not enforced.'
    )
    allowedBundleIds: Optional[List[str]] = Field(
        None,
        description="iOS bundle ids of apps allowed to use the key. Example: 'com.companyname.productname.appname'",
    )


class GoogleCloudRecaptchaenterpriseV1MigrateKeyRequest(BaseModel):
    skipBillingCheck: Optional[bool] = Field(
        None,
        description='Optional. If true, skips the billing check. A reCAPTCHA Enterprise key or migrated key behaves differently than a reCAPTCHA (non-Enterprise version) key when you reach a quota limit (see https://cloud.google.com/recaptcha-enterprise/quotas#quota_limit). To avoid any disruption of your usage, we check that a billing account is present. If your usage of reCAPTCHA is under the free quota, you can safely skip the billing check and proceed with the migration. See https://cloud.google.com/recaptcha-enterprise/docs/billing-information.',
    )


class GoogleCloudRecaptchaenterpriseV1PrivatePasswordLeakVerification(BaseModel):
    encryptedLeakMatchPrefixes: Optional[List[str]] = Field(
        None,
        description='Output only. List of prefixes of the encrypted potential password leaks that matched the given parameters. They must be compared with the client-side decryption prefix of `reencrypted_user_credentials_hash`',
    )
    encryptedUserCredentialsHash: Optional[str] = Field(
        None,
        description='Optional. Encrypted Scrypt hash of the canonicalized username+password. It is re-encrypted by the server and returned through `reencrypted_user_credentials_hash`.',
    )
    lookupHashPrefix: Optional[str] = Field(
        None,
        description='Optional. Exactly 26-bit prefix of the SHA-256 hash of the canonicalized username. It is used to look up password leaks associated with that hash prefix.',
    )
    reencryptedUserCredentialsHash: Optional[str] = Field(
        None,
        description='Output only. Corresponds to the re-encryption of the `encrypted_user_credentials_hash` field. It is used to match potential password leaks within `encrypted_leak_match_prefixes`.',
    )


class GoogleCloudRecaptchaenterpriseV1RelatedAccountGroup(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. The resource name for the related account group in the format `projects/{project}/relatedaccountgroups/{related_account_group}`.',
    )


class GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupMembership(BaseModel):
    hashedAccountId: Optional[str] = Field(
        None,
        description='The unique stable hashed user identifier of the member. The identifier corresponds to a `hashed_account_id` provided in a previous `CreateAssessment` or `AnnotateAssessment` call.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. The resource name for this membership in the format `projects/{project}/relatedaccountgroups/{relatedaccountgroup}/memberships/{membership}`.',
    )


class GoogleCloudRecaptchaenterpriseV1RetrieveLegacySecretKeyResponse(BaseModel):
    legacySecretKey: Optional[str] = Field(
        None,
        description='The secret key (also known as shared secret) authorizes communication between your application backend and the reCAPTCHA Enterprise server to create an assessment. The secret key needs to be kept safe for security purposes.',
    )


class Reason1(Enum):
    CLASSIFICATION_REASON_UNSPECIFIED = 'CLASSIFICATION_REASON_UNSPECIFIED'
    AUTOMATION = 'AUTOMATION'
    UNEXPECTED_ENVIRONMENT = 'UNEXPECTED_ENVIRONMENT'
    TOO_MUCH_TRAFFIC = 'TOO_MUCH_TRAFFIC'
    UNEXPECTED_USAGE_PATTERNS = 'UNEXPECTED_USAGE_PATTERNS'
    LOW_CONFIDENCE_SCORE = 'LOW_CONFIDENCE_SCORE'
    SUSPECTED_CARDING = 'SUSPECTED_CARDING'
    SUSPECTED_CHARGEBACK = 'SUSPECTED_CHARGEBACK'


class GoogleCloudRecaptchaenterpriseV1RiskAnalysis(BaseModel):
    extendedVerdictReasons: Optional[List[str]] = Field(
        None,
        description='Extended verdict reasons to be used for experimentation only. The set of possible reasons is subject to change.',
    )
    reasons: Optional[List[Reason1]] = Field(
        None, description='Reasons contributing to the risk analysis verdict.'
    )
    score: Optional[float] = Field(
        None,
        description='Legitimate event score from 0.0 to 1.0. (1.0 means very likely legitimate traffic while 0.0 means very likely non-legitimate traffic).',
    )


class GoogleCloudRecaptchaenterpriseV1ScoreDistribution(BaseModel):
    scoreBuckets: Optional[Dict[str, str]] = Field(
        None,
        description='Map key is score value multiplied by 100. The scores are discrete values between [0, 1]. The maximum number of buckets is on order of a few dozen, but typically much lower (ie. 10).',
    )


class GoogleCloudRecaptchaenterpriseV1ScoreMetrics(BaseModel):
    actionMetrics: Optional[
        Dict[str, GoogleCloudRecaptchaenterpriseV1ScoreDistribution]
    ] = Field(
        None,
        description='Action-based metrics. The map key is the action name which specified by the site owners at time of the "execute" client-side call.',
    )
    overallMetrics: Optional[GoogleCloudRecaptchaenterpriseV1ScoreDistribution] = Field(
        None, description='Aggregated score metrics for all traffic.'
    )


class GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsRequest(
    BaseModel
):
    hashedAccountId: Optional[str] = Field(
        None,
        description='Optional. The unique stable hashed user identifier we should search connections to. The identifier should correspond to a `hashed_account_id` provided in a previous `CreateAssessment` or `AnnotateAssessment` call.',
    )
    pageSize: Optional[int] = Field(
        None,
        description='Optional. The maximum number of groups to return. The service might return fewer than this value. If unspecified, at most 50 groups are returned. The maximum value is 1000; values above 1000 are coerced to 1000.',
    )
    pageToken: Optional[str] = Field(
        None,
        description='Optional. A page token, received from a previous `SearchRelatedAccountGroupMemberships` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `SearchRelatedAccountGroupMemberships` must match the call that provided the page token.',
    )


class GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsResponse(
    BaseModel
):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    relatedAccountGroupMemberships: Optional[
        List[GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupMembership]
    ] = Field(None, description='The queried memberships.')


class TestingChallenge(Enum):
    TESTING_CHALLENGE_UNSPECIFIED = 'TESTING_CHALLENGE_UNSPECIFIED'
    NOCAPTCHA = 'NOCAPTCHA'
    UNSOLVABLE_CHALLENGE = 'UNSOLVABLE_CHALLENGE'


class GoogleCloudRecaptchaenterpriseV1TestingOptions(BaseModel):
    testingChallenge: Optional[TestingChallenge] = Field(
        None,
        description='For challenge-based keys only (CHECKBOX, INVISIBLE), all challenge requests for this site will return nocaptcha if NOCAPTCHA, or an unsolvable challenge if CHALLENGE.',
    )
    testingScore: Optional[float] = Field(
        None,
        description='All assessments for this Key will return this score. Must be between 0 (likely not legitimate) and 1 (likely legitimate) inclusive.',
    )


class InvalidReason(Enum):
    INVALID_REASON_UNSPECIFIED = 'INVALID_REASON_UNSPECIFIED'
    UNKNOWN_INVALID_REASON = 'UNKNOWN_INVALID_REASON'
    MALFORMED = 'MALFORMED'
    EXPIRED = 'EXPIRED'
    DUPE = 'DUPE'
    MISSING = 'MISSING'
    BROWSER_ERROR = 'BROWSER_ERROR'


class GoogleCloudRecaptchaenterpriseV1TokenProperties(BaseModel):
    action: Optional[str] = Field(
        None, description='Action name provided at token generation.'
    )
    androidPackageName: Optional[str] = Field(
        None,
        description='The name of the Android package with which the token was generated (Android keys only).',
    )
    createTime: Optional[str] = Field(
        None, description='The timestamp corresponding to the generation of the token.'
    )
    hostname: Optional[str] = Field(
        None,
        description='The hostname of the page on which the token was generated (Web keys only).',
    )
    invalidReason: Optional[InvalidReason] = Field(
        None, description='Reason associated with the response when valid = false.'
    )
    iosBundleId: Optional[str] = Field(
        None,
        description='The ID of the iOS bundle with which the token was generated (iOS keys only).',
    )
    valid: Optional[bool] = Field(
        None,
        description='Whether the provided user response token is valid. When valid = false, the reason could be specified in invalid_reason or it could also be due to a user failing to solve a challenge or a sitekey mismatch (i.e the sitekey used to generate the token was different than the one specified in the assessment).',
    )


class GoogleCloudRecaptchaenterpriseV1TransactionDataAddress(BaseModel):
    address: Optional[List[str]] = Field(
        None,
        description='The first lines of the address. The first line generally contains the street name and number, and further lines may include information such as an apartment number.',
    )
    administrativeArea: Optional[str] = Field(
        None,
        description='The state, province, or otherwise administrative area of the address.',
    )
    locality: Optional[str] = Field(None, description='The town/city of the address.')
    postalCode: Optional[str] = Field(
        None, description='The postal or ZIP code of the address.'
    )
    recipient: Optional[str] = Field(
        None,
        description='The recipient name, potentially including information such as "care of".',
    )
    regionCode: Optional[str] = Field(
        None, description='The CLDR country/region of the address.'
    )


class GoogleCloudRecaptchaenterpriseV1TransactionDataGatewayInfo(BaseModel):
    avsResponseCode: Optional[str] = Field(
        None,
        description='AVS response code from the gateway (available only when reCAPTCHA Enterprise is called after authorization).',
    )
    cvvResponseCode: Optional[str] = Field(
        None,
        description='CVV response code from the gateway (available only when reCAPTCHA Enterprise is called after authorization).',
    )
    gatewayResponseCode: Optional[str] = Field(
        None,
        description='Gateway response code describing the state of the transaction.',
    )
    name: Optional[str] = Field(
        None,
        description='Name of the gateway service (for example, stripe, square, paypal).',
    )


class GoogleCloudRecaptchaenterpriseV1TransactionDataItem(BaseModel):
    merchantAccountId: Optional[str] = Field(
        None,
        description='When a merchant is specified, its corresponding account_id. Necessary to populate marketplace-style transactions.',
    )
    name: Optional[str] = Field(None, description='The full name of the item.')
    quantity: Optional[str] = Field(
        None, description='The quantity of this item that is being purchased.'
    )
    value: Optional[float] = Field(
        None,
        description='The value per item that the user is paying, in the transaction currency, after discounts.',
    )


class GoogleCloudRecaptchaenterpriseV1TransactionDataUser(BaseModel):
    accountId: Optional[str] = Field(
        None,
        description='Unique account identifier for this user. If using account defender, this should match the hashed_account_id field. Otherwise, a unique and persistent identifier for this account.',
    )
    creationMs: Optional[str] = Field(
        None, description="The epoch milliseconds of the user's account creation."
    )
    email: Optional[str] = Field(None, description='The email address of the user.')
    emailVerified: Optional[bool] = Field(
        None,
        description='Whether the email has been verified to be accessible by the user (OTP or similar).',
    )
    phoneNumber: Optional[str] = Field(
        None, description='The phone number of the user, with country code.'
    )
    phoneVerified: Optional[bool] = Field(
        None,
        description='Whether the phone number has been verified to be accessible by the user (OTP or similar).',
    )


class EventType(Enum):
    TRANSACTION_EVENT_TYPE_UNSPECIFIED = 'TRANSACTION_EVENT_TYPE_UNSPECIFIED'
    MERCHANT_APPROVE = 'MERCHANT_APPROVE'
    MERCHANT_DENY = 'MERCHANT_DENY'
    MANUAL_REVIEW = 'MANUAL_REVIEW'
    AUTHORIZATION = 'AUTHORIZATION'
    AUTHORIZATION_DECLINE = 'AUTHORIZATION_DECLINE'
    PAYMENT_CAPTURE = 'PAYMENT_CAPTURE'
    PAYMENT_CAPTURE_DECLINE = 'PAYMENT_CAPTURE_DECLINE'
    CANCEL = 'CANCEL'
    CHARGEBACK_INQUIRY = 'CHARGEBACK_INQUIRY'
    CHARGEBACK_ALERT = 'CHARGEBACK_ALERT'
    FRAUD_NOTIFICATION = 'FRAUD_NOTIFICATION'
    CHARGEBACK = 'CHARGEBACK'
    CHARGEBACK_REPRESENTMENT = 'CHARGEBACK_REPRESENTMENT'
    CHARGEBACK_REVERSE = 'CHARGEBACK_REVERSE'
    REFUND_REQUEST = 'REFUND_REQUEST'
    REFUND_DECLINE = 'REFUND_DECLINE'
    REFUND = 'REFUND'
    REFUND_REVERSE = 'REFUND_REVERSE'


class GoogleCloudRecaptchaenterpriseV1TransactionEvent(BaseModel):
    eventTime: Optional[str] = Field(
        None,
        description='Optional. Timestamp when this transaction event occurred; otherwise assumed to be the time of the API call.',
    )
    eventType: Optional[EventType] = Field(
        None, description='Optional. The type of this transaction event.'
    )
    reason: Optional[str] = Field(
        None,
        description='Optional. The reason or standardized code that corresponds with this transaction event, if one exists. For example, a CHARGEBACK event with code 6005.',
    )
    value: Optional[float] = Field(
        None,
        description='Optional. The value that corresponds with this transaction event, if one exists. For example, a refund event where $5.00 was refunded. Currency is obtained from the original transaction data.',
    )


class WafFeature(Enum):
    WAF_FEATURE_UNSPECIFIED = 'WAF_FEATURE_UNSPECIFIED'
    CHALLENGE_PAGE = 'CHALLENGE_PAGE'
    SESSION_TOKEN = 'SESSION_TOKEN'
    ACTION_TOKEN = 'ACTION_TOKEN'
    EXPRESS = 'EXPRESS'


class WafService(Enum):
    WAF_SERVICE_UNSPECIFIED = 'WAF_SERVICE_UNSPECIFIED'
    CA = 'CA'
    FASTLY = 'FASTLY'


class GoogleCloudRecaptchaenterpriseV1WafSettings(BaseModel):
    wafFeature: Optional[WafFeature] = Field(
        None, description='Required. The WAF feature for which this key is enabled.'
    )
    wafService: Optional[WafService] = Field(
        None, description='Required. The WAF service that uses this key.'
    )


class ChallengeSecurityPreference(Enum):
    CHALLENGE_SECURITY_PREFERENCE_UNSPECIFIED = (
        'CHALLENGE_SECURITY_PREFERENCE_UNSPECIFIED'
    )
    USABILITY = 'USABILITY'
    BALANCE = 'BALANCE'
    SECURITY = 'SECURITY'


class IntegrationType(Enum):
    INTEGRATION_TYPE_UNSPECIFIED = 'INTEGRATION_TYPE_UNSPECIFIED'
    SCORE = 'SCORE'
    CHECKBOX = 'CHECKBOX'
    INVISIBLE = 'INVISIBLE'


class GoogleCloudRecaptchaenterpriseV1WebKeySettings(BaseModel):
    allowAllDomains: Optional[bool] = Field(
        None,
        description='If set to true, it means allowed_domains will not be enforced.',
    )
    allowAmpTraffic: Optional[bool] = Field(
        None,
        description='If set to true, the key can be used on AMP (Accelerated Mobile Pages) websites. This is supported only for the SCORE integration type.',
    )
    allowedDomains: Optional[List[str]] = Field(
        None,
        description="Domains or subdomains of websites allowed to use the key. All subdomains of an allowed domain are automatically allowed. A valid domain requires a host and must not include any path, port, query or fragment. Examples: 'example.com' or 'subdomain.example.com'",
    )
    challengeSecurityPreference: Optional[ChallengeSecurityPreference] = Field(
        None,
        description='Settings for the frequency and difficulty at which this key triggers captcha challenges. This should only be specified for IntegrationTypes CHECKBOX and INVISIBLE.',
    )
    integrationType: Optional[IntegrationType] = Field(
        None,
        description='Required. Describes how this key is integrated with the website.',
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleRpcStatus(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudRecaptchaenterpriseV1AccountVerificationInfo(BaseModel):
    endpoints: Optional[
        List[GoogleCloudRecaptchaenterpriseV1EndpointVerificationInfo]
    ] = Field(None, description='Endpoints that can be used for identity verification.')
    languageCode: Optional[str] = Field(
        None,
        description='Language code preference for the verification message, set as a IETF BCP 47 language code.',
    )
    latestVerificationResult: Optional[LatestVerificationResult] = Field(
        None,
        description='Output only. Result of the latest account verification challenge.',
    )
    username: Optional[str] = Field(
        None,
        description='Username of the account that is being verified. Deprecated. Customers should now provide the hashed account ID field in Event.',
    )


class GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentRequest(BaseModel):
    annotation: Optional[Annotation] = Field(
        None,
        description='Optional. The annotation that will be assigned to the Event. This field can be left empty to provide reasons that apply to an event without concluding whether the event is legitimate or fraudulent.',
    )
    hashedAccountId: Optional[str] = Field(
        None,
        description='Optional. Unique stable hashed user identifier to apply to the assessment. This is an alternative to setting the hashed_account_id in CreateAssessment, for example when the account identifier is not yet known in the initial request. It is recommended that the identifier is hashed using hmac-sha256 with stable secret.',
    )
    reasons: Optional[List[Reason]] = Field(
        None,
        description='Optional. Optional reasons for the annotation that will be assigned to the Event.',
    )
    transactionEvent: Optional[GoogleCloudRecaptchaenterpriseV1TransactionEvent] = (
        Field(
            None,
            description='Optional. If the assessment is part of a payment transaction, provide details on payment lifecycle events that occur in the transaction.',
        )
    )


class GoogleCloudRecaptchaenterpriseV1FirewallAction(BaseModel):
    allow: Optional[GoogleCloudRecaptchaenterpriseV1FirewallActionAllowAction] = Field(
        None,
        description='The user request did not match any policy and should be allowed access to the requested resource.',
    )
    block: Optional[GoogleCloudRecaptchaenterpriseV1FirewallActionBlockAction] = Field(
        None,
        description='This action will deny access to a given page. The user will get an HTTP error code.',
    )
    redirect: Optional[GoogleCloudRecaptchaenterpriseV1FirewallActionRedirectAction] = (
        Field(
            None,
            description='This action will redirect the request to a ReCaptcha interstitial to attach a token.',
        )
    )
    setHeader: Optional[
        GoogleCloudRecaptchaenterpriseV1FirewallActionSetHeaderAction
    ] = Field(
        None,
        description='This action will set a custom header but allow the request to continue to the customer backend.',
    )
    substitute: Optional[
        GoogleCloudRecaptchaenterpriseV1FirewallActionSubstituteAction
    ] = Field(
        None,
        description='This action will transparently serve a different page to an offending user.',
    )


class GoogleCloudRecaptchaenterpriseV1FirewallPolicy(BaseModel):
    actions: Optional[List[GoogleCloudRecaptchaenterpriseV1FirewallAction]] = Field(
        None,
        description='The actions that the caller should take regarding user access. There should be at most one terminal action. A terminal action is any action that forces a response, such as AllowAction, BlockAction or SubstituteAction. Zero or more non-terminal actions such as SetHeader might be specified. A single policy can contain up to 16 actions.',
    )
    condition: Optional[str] = Field(
        None,
        description='A CEL (Common Expression Language) conditional expression that specifies if this policy applies to an incoming user request. If this condition evaluates to true and the requested path matched the path pattern, the associated actions should be executed by the caller. The condition string is checked for CEL syntax correctness on creation. For more information, see the [CEL spec](https://github.com/google/cel-spec) and its [language definition](https://github.com/google/cel-spec/blob/master/doc/langdef.md). A condition has a max length of 500 characters.',
    )
    description: Optional[str] = Field(
        None,
        description='A description of what this policy aims to achieve, for convenience purposes. The description can at most include 256 UTF-8 characters.',
    )
    name: Optional[str] = Field(
        None,
        description='The resource name for the FirewallPolicy in the format "projects/{project}/firewallpolicies/{firewallpolicy}".',
    )
    path: Optional[str] = Field(
        None,
        description='The path for which this policy applies, specified as a glob pattern. For more information on glob, see the [manual page](https://man7.org/linux/man-pages/man7/glob.7.html). A path has a max length of 200 characters.',
    )


class GoogleCloudRecaptchaenterpriseV1FirewallPolicyAssessment(BaseModel):
    error: Optional[GoogleRpcStatus] = Field(
        None,
        description='If the processing of a policy config fails, an error will be populated and the firewall_policy will be left empty.',
    )
    firewallPolicy: Optional[GoogleCloudRecaptchaenterpriseV1FirewallPolicy] = Field(
        None,
        description='Output only. The policy that matched the request. If more than one policy may match, this is the first match. If no policy matches the incoming request, the policy field will be left empty.',
    )


class GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessment(BaseModel):
    behavioralTrustVerdict: Optional[
        GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentBehavioralTrustVerdict
    ] = Field(None, description='Assessment of this transaction for behavioral trust.')
    cardTestingVerdict: Optional[
        GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentCardTestingVerdict
    ] = Field(
        None,
        description='Assessment of this transaction for risk of being part of a card testing attack.',
    )
    stolenInstrumentVerdict: Optional[
        GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentStolenInstrumentVerdict
    ] = Field(
        None,
        description='Assessment of this transaction for risk of a stolen instrument.',
    )
    transactionRisk: Optional[float] = Field(
        None,
        description='Probability (0-1) of this transaction being fraudulent. Summarizes the combined risk of attack vectors below.',
    )


class GoogleCloudRecaptchaenterpriseV1Key(BaseModel):
    androidSettings: Optional[GoogleCloudRecaptchaenterpriseV1AndroidKeySettings] = (
        Field(None, description='Settings for keys that can be used by Android apps.')
    )
    createTime: Optional[str] = Field(
        None,
        description='Output only. The timestamp corresponding to the creation of this key.',
    )
    displayName: Optional[str] = Field(
        None, description='Human-readable display name of this key. Modifiable by user.'
    )
    iosSettings: Optional[GoogleCloudRecaptchaenterpriseV1IOSKeySettings] = Field(
        None, description='Settings for keys that can be used by iOS apps.'
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='See Creating and managing labels.'
    )
    name: Optional[str] = Field(
        None,
        description='The resource name for the Key in the format "projects/{project}/keys/{key}".',
    )
    testingOptions: Optional[GoogleCloudRecaptchaenterpriseV1TestingOptions] = Field(
        None, description='Options for user acceptance testing.'
    )
    wafSettings: Optional[GoogleCloudRecaptchaenterpriseV1WafSettings] = Field(
        None, description='Settings for WAF'
    )
    webSettings: Optional[GoogleCloudRecaptchaenterpriseV1WebKeySettings] = Field(
        None, description='Settings for keys that can be used by websites.'
    )


class GoogleCloudRecaptchaenterpriseV1ListFirewallPoliciesResponse(BaseModel):
    firewallPolicies: Optional[List[GoogleCloudRecaptchaenterpriseV1FirewallPolicy]] = (
        Field(None, description='Policy details.')
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results. It is set to empty if no policies remain in results.',
    )


class GoogleCloudRecaptchaenterpriseV1ListKeysResponse(BaseModel):
    keys: Optional[List[GoogleCloudRecaptchaenterpriseV1Key]] = Field(
        None, description='Key details.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results. It is set to empty if no keys remain in results.',
    )


class GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupMembershipsResponse(
    BaseModel
):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    relatedAccountGroupMemberships: Optional[
        List[GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupMembership]
    ] = Field(None, description='The memberships listed by the query.')


class GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    relatedAccountGroups: Optional[
        List[GoogleCloudRecaptchaenterpriseV1RelatedAccountGroup]
    ] = Field(None, description='The groups of related accounts listed by the query.')


class GoogleCloudRecaptchaenterpriseV1Metrics(BaseModel):
    challengeMetrics: Optional[
        List[GoogleCloudRecaptchaenterpriseV1ChallengeMetrics]
    ] = Field(
        None,
        description='Metrics will be continuous and in order by dates, and in the granularity of day. Only challenge-based keys (CHECKBOX, INVISIBLE), will have challenge-based data.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The name of the metrics, in the format "projects/{project}/keys/{key}/metrics".',
    )
    scoreMetrics: Optional[List[GoogleCloudRecaptchaenterpriseV1ScoreMetrics]] = Field(
        None,
        description='Metrics will be continuous and in order by dates, and in the granularity of day. All Key types should have score-based data.',
    )
    startTime: Optional[str] = Field(
        None, description='Inclusive start time aligned to a day (UTC).'
    )


class GoogleCloudRecaptchaenterpriseV1TransactionData(BaseModel):
    billingAddress: Optional[GoogleCloudRecaptchaenterpriseV1TransactionDataAddress] = (
        Field(
            None,
            description='Address associated with the payment method when applicable.',
        )
    )
    cardBin: Optional[str] = Field(
        None,
        description='The Bank Identification Number - generally the first 6 or 8 digits of the card.',
    )
    cardLastFour: Optional[str] = Field(
        None, description='The last four digits of the card.'
    )
    currencyCode: Optional[str] = Field(
        None, description='The currency code in ISO-4217 format.'
    )
    gatewayInfo: Optional[
        GoogleCloudRecaptchaenterpriseV1TransactionDataGatewayInfo
    ] = Field(
        None,
        description="Information about the payment gateway's response to the transaction.",
    )
    items: Optional[List[GoogleCloudRecaptchaenterpriseV1TransactionDataItem]] = Field(
        None, description='Items purchased in this transaction.'
    )
    merchants: Optional[List[GoogleCloudRecaptchaenterpriseV1TransactionDataUser]] = (
        Field(
            None,
            description='Information about the user or users fulfilling the transaction.',
        )
    )
    paymentMethod: Optional[str] = Field(
        None,
        description='The payment method for the transaction. The allowed values are: * credit-card * debit-card * gift-card * processor-{name} (If a third-party is used, for example, processor-paypal) * custom-{name} (If an alternative method is used, for example, custom-crypto)',
    )
    shippingAddress: Optional[
        GoogleCloudRecaptchaenterpriseV1TransactionDataAddress
    ] = Field(
        None,
        description='Destination address if this transaction involves shipping a physical item.',
    )
    shippingValue: Optional[float] = Field(
        None,
        description='The value of shipping in the specified currency. 0 for free or no shipping.',
    )
    transactionId: Optional[str] = Field(
        None,
        description='Unique identifier for the transaction. This custom identifier can be used to reference this transaction in the future, for example, labeling a refund or chargeback event. Two attempts at the same transaction should use the same transaction id.',
    )
    user: Optional[GoogleCloudRecaptchaenterpriseV1TransactionDataUser] = Field(
        None,
        description='Information about the user paying/initiating the transaction.',
    )
    value: Optional[float] = Field(
        None,
        description='The decimal value of the transaction in the specified currency.',
    )


class GoogleCloudRecaptchaenterpriseV1Event(BaseModel):
    expectedAction: Optional[str] = Field(
        None,
        description='Optional. The expected action for this type of event. This should be the same action provided at token generation time on client-side platforms already integrated with recaptcha enterprise.',
    )
    express: Optional[bool] = Field(
        None,
        description='Optional. Flag for a reCAPTCHA express request for an assessment without a token. If enabled, `site_key` must reference a SCORE key with WAF feature set to EXPRESS.',
    )
    firewallPolicyEvaluation: Optional[bool] = Field(
        None,
        description='Optional. Flag for enabling firewall policy config assessment. If this flag is enabled, the firewall policy will be evaluated and a suggested firewall action will be returned in the response.',
    )
    hashedAccountId: Optional[str] = Field(
        None,
        description='Optional. Unique stable hashed user identifier for the request. The identifier must be hashed using hmac-sha256 with stable secret.',
    )
    headers: Optional[List[str]] = Field(
        None, description='Optional. HTTP header information about the request.'
    )
    ja3: Optional[str] = Field(
        None, description='Optional. Optional JA3 fingerprint for SSL clients.'
    )
    requestedUri: Optional[str] = Field(
        None,
        description='Optional. The URI resource the user requested that triggered an assessment.',
    )
    siteKey: Optional[str] = Field(
        None,
        description='Optional. The site key that was used to invoke reCAPTCHA Enterprise on your site and generate the token.',
    )
    token: Optional[str] = Field(
        None,
        description='Optional. The user response token provided by the reCAPTCHA Enterprise client-side integration on your site.',
    )
    transactionData: Optional[GoogleCloudRecaptchaenterpriseV1TransactionData] = Field(
        None,
        description='Optional. Data describing a payment transaction to be assessed. Sending this data enables reCAPTCHA Enterprise Fraud Prevention and the FraudPreventionAssessment component in the response.',
    )
    userAgent: Optional[str] = Field(
        None,
        description="Optional. The user agent present in the request from the user's device related to this event.",
    )
    userIpAddress: Optional[str] = Field(
        None,
        description="Optional. The IP address in the request from the user's device related to this event.",
    )
    wafTokenAssessment: Optional[bool] = Field(
        None,
        description='Optional. Flag for running WAF token assessment. If enabled, the token must be specified, and have been created by a WAF-enabled key.',
    )


class GoogleCloudRecaptchaenterpriseV1Assessment(BaseModel):
    accountDefenderAssessment: Optional[
        GoogleCloudRecaptchaenterpriseV1AccountDefenderAssessment
    ] = Field(
        None,
        description='Assessment returned by account defender when a hashed_account_id is provided.',
    )
    accountVerification: Optional[
        GoogleCloudRecaptchaenterpriseV1AccountVerificationInfo
    ] = Field(
        None,
        description='Account verification information for identity verification. The assessment event must include a token and site key to use this feature.',
    )
    event: Optional[GoogleCloudRecaptchaenterpriseV1Event] = Field(
        None, description='The event being assessed.'
    )
    firewallPolicyAssessment: Optional[
        GoogleCloudRecaptchaenterpriseV1FirewallPolicyAssessment
    ] = Field(
        None,
        description='Assessment returned when firewall policies belonging to the project are evaluated using the field firewall_policy_evaluation.',
    )
    fraudPreventionAssessment: Optional[
        GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessment
    ] = Field(
        None,
        description='Assessment returned by Fraud Prevention when TransactionData is provided.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name for the Assessment in the format "projects/{project}/assessments/{assessment}".',
    )
    privatePasswordLeakVerification: Optional[
        GoogleCloudRecaptchaenterpriseV1PrivatePasswordLeakVerification
    ] = Field(
        None,
        description='The private password leak verification field contains the parameters that are used to to check for leaks privately without sharing user credentials.',
    )
    riskAnalysis: Optional[GoogleCloudRecaptchaenterpriseV1RiskAnalysis] = Field(
        None,
        description='Output only. The risk analysis result for the event being assessed.',
    )
    tokenProperties: Optional[GoogleCloudRecaptchaenterpriseV1TokenProperties] = Field(
        None, description='Output only. Properties of the provided event token.'
    )
